[build-system]
requires = ["briefcase"]

[tool.briefcase]
project_name = "Layout Test"
bundle = "org.beeware"
version = "0.0.1"
url = "https://beeware.org"
license = "BSD license"
author = 'Tiberius Yak'
author_email = "tiberius@beeware.org"

[tool.briefcase.app.tayout_test]
formal_name = "Layout Test"
description = "A testing app"
sources = ['tayout_test']
requires = []


[tool.briefcase.app.tayout_test.macOS]
requires = [
    'toga-cocoa',
]

[tool.briefcase.app.tayout_test.linux]
requires = [
    'toga-gtk',
]

[tool.briefcase.app.tayout_test.windows]
requires = [
    'toga-winforms',
]

# Mobile deployments
[tool.briefcase.app.tayout_test.iOS]
requires = [
    'toga-iOS',
]

[tool.briefcase.app.tayout_test.android]
requires = [
    'toga-android',
]
